server:
  port: 8060
spring:
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    smtp:
      auth: true
    properties:
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest