spring:
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true
  cloud:
    stream:
      bindings:
        sendConfirmationMailChannel:
          durableSubscription: true
          group: default
          destination: send-confirmation-mail-queue
          content-type: application/x-java-object;type=com.javangarda.fantacalcio.mail.application.data.commands.ConfirmEmailCommand