spring:
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    smtp:
      auth: true
    properties:
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:sqlite:fantacalcio_db_mail.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: that.custom.SQLiteDialect