spring:
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true
  cloud:
    stream:
      bindings:
        sendConfirmationMailChannel:
          durableSubscription: true
          group: default
          destination: user-registered-queue
          content-type: application/x-java-object;type=com.javangarda.fantacalcio.mail.infrastructure.adapter.income.messaging.model.UserRegisteredEvent
        userAttemptedToChangeEmailChannel:
          durableSubscription: true
          group: default
          destination: user-attempted-to-change-email-queue
          content-type: application/x-java-object;type=com.javangarda.fantacalcio.mail.infrastructure.adapter.income.messaging.model.UserAttemptedToChangeEmailEvent
        userForgotPasswordChannel:
          durableSubscription: true
          group: default
          destination: user-forgot-password-queue
          content-type: application/x-java-object;type=com.javangarda.fantacalcio.mail.infrastructure.adapter.income.messaging.model.UserForgotPasswordEvent
  application:
    name: fantacalcio-mail
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC